# Site settings
title: Oakland University William Beaumont School of Medicine
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Oakland University William Beaumont School of Medicine
user_description: We are students. We are future physcians. We are the OUWB Class of 2024. Welcome to our homepage. We hope this site will serve as a hub for resources, advice, and accomplishements from our whole class. 
user_title: Class of 2024
email: 
# twitter_username: lorem_ipsum
# github_username:  
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
